kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
# uncomment below content to enable nodes to pull images from our exclusive docker registry
#containerdConfigPatches:
#  - |
#    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
#      endpoint = ["http://128.105.144.30:5000"]
nodes:
  - role: control-plane
    image: jacksonarthurclark/aiopslab-kind-x86@sha256:d631857278d3f8ce5c36364c75ec25695ceb22e311ec6621a4ebf5506b86774d
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: worker
    image: jacksonarthurclark/aiopslab-kind-x86@sha256:d631857278d3f8ce5c36364c75ec25695ceb22e311ec6621a4ebf5506b86774d
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: worker
    image: jacksonarthurclark/aiopslab-kind-x86@sha256:d631857278d3f8ce5c36364c75ec25695ceb22e311ec6621a4ebf5506b86774d
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
  - role: worker
    image: jacksonarthurclark/aiopslab-kind-x86@sha256:d631857278d3f8ce5c36364c75ec25695ceb22e311ec6621a4ebf5506b86774d
    extraMounts:
      - hostPath: /run/udev
        containerPath: /run/udev
