"""CASSANDRA-16334 — replica failure causes WriteTimeout on a multi-DC write, on the raw-ring harness.

JIRA: https://issues.apache.org/jira/browse/CASSANDRA-16334
Buggy: 4.0.1  ->  Fixed: 4.0.2 (A/B control = cassandra:4.0.2).
Components: Consistency/Coordination, Messaging/Internode.

THE BUG (a real TWO-datacenter ring; RF=1/DC is sufficient — the mechanism is RF-independent):
  On a ring with two named datacenters (dc1 + dc2, GossipingPropertyFileSnitch) and a
  ``NetworkTopologyStrategy{dc1:1, dc2:1}`` keyspace, an oversized mutation (larger than
  ``max_mutation_size_in_kb``) issued at CONSISTENCY ``LOCAL_ONE`` is rejected by every replica. On the
  buggy 4.0.1 multi-DC coordinator path the write WRONGLY surfaces a ``WriteTimeout`` (code=1100) instead
  of the correct ``WriteFailure`` (code=1500). The defect: the write-response handler counts total
  replicas across ALL DCs but only tallies failure responses from the LOCAL DC, so the failure threshold
  ``blockFor() + failures > candidateReplicaCount()`` never trips (candidateReplicaCount() uses the all-DC
  count while ``failures`` only accrues local-DC failures); the coordinator waits out the full write
  timeout. The SAME image + SAME workload on a SINGLE-DC keyspace (dc1:1) instead returns the CORRECT
  WriteFailure (code=1500) — isolating the defect to the multi-DC path. The fix (4.0.2) makes
  candidateReplicaCount() return the local-DC count when ``consistencyLevel().isDatacenterLocal()``.

  The consistency level MUST be ``LOCAL_ONE``: cqlsh's default ``ONE`` routes through the all-DC
  WriteResponseHandler failure count and would mask the bug.

VERBATIM BUGGY SIGNATURE (literal cqlsh output of the LOCAL_ONE insert against the multi-DC keyspace):
  WriteTimeout: Error from server: code=1100 [Coordinator node timed out waiting for replica nodes'
  responses] message="Operation timed out - received only 0 responses." info={'consistency': 'LOCAL_ONE',
  'required_responses': 1, 'received_responses': 0, 'write_type': 'SIMPLE'}

Fixed 4.0.2 returns, for the identical 2-DC topology and identical workload:
  WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] ... 'failures': 1 ...

HOW THE RAW-RING HARNESS MAKES THIS RUNNABLE (the former multi-DC blocker, resolved):
  * Topology — ``CassandraRawRingApplication`` deploys two bare pods, ONE per datacenter, on the stock
    ``cassandra:4.0.1`` image: ``cass-dc1`` (self-seeded, ``CASSANDRA_DC=dc1``) and ``cass-dc2``
    (``CASSANDRA_DC=dc2``, seeded off cass-dc1) under GossipingPropertyFileSnitch. ``replicas=0`` (no
    StatefulSet) because both nodes need a per-pod DC + an appended ``max_mutation_size_in_kb`` in
    cassandra.yaml, so each is created with a custom command in ``post_deploy``.
  * Oversized-mutation precondition — ``max_mutation_size_in_kb: 1000`` is appended to cassandra.yaml on
    BOTH nodes; ``inject_fault`` stages a 1.1 MB blob (2.2 MB hex) CQL file in-pod (generated by python3,
    avoiding ARG_MAX) so every replica rejects the mutation.
  * Detection — the only discriminator is the cqlsh error code (1100 buggy vs 1500 fixed), so
    ``CassandraLogGrepOracle(source='command')`` runs the LOCAL_ONE ``cqlsh -f`` insert on cass-dc1 and
    greps its output for the verbatim ``code=1100 [Coordinator node timed out ...]`` WriteTimeout line.

Verified end-to-end on kind-fleet3: the multi-DC LOCAL_ONE insert emits ``code=1100`` (WriteTimeout) on
4.0.1, while the SAME buggy image returns ``code=1500`` (WriteFailure) on a single-DC keyspace — the A/B
control proving the bug is the multi-DC coordinator path (a fixed 4.0.2 binary returns code=1500 here too).
"""

import logging

from sregym.conductor.oracles.cassandra_raw_ring_oracles import CassandraLogGrepOracle
from sregym.conductor.problems.cassandra_raw_ring import CassandraRawRingProblem
from sregym.utils.decorators import mark_fault_injected

logger = logging.getLogger(__name__)


class AutoCassandra16334(CassandraRawRingProblem):
    """Two-DC ring (dc1 + dc2); an oversized LOCAL_ONE write yields WriteTimeout (4.0.1) not WriteFailure."""

    db_name = "cassandra"
    db_version = "4.0.1"
    cassandra_version = "4.0.1"
    source_git_ref = "cassandra-4.0.1"
    ring_namespace = "cassraw-16334"
    # No StatefulSet ring: both DC nodes are bare pods created in post_deploy with a per-pod
    # CASSANDRA_DC and an appended max_mutation_size_in_kb (neither is expressible via the fixed
    # StatefulSet command).
    replicas = 0

    root_cause_file = "src/java/org/apache/cassandra/service/AbstractWriteResponseHandler.java"
    root_cause_description = (
        "Replica failure wrongly causes a WriteTimeout instead of a WriteFailure on a "
        "multi-DC write with a DC-local consistency level (LOCAL_ONE). When an oversized "
        "mutation (larger than max_mutation_size_in_kb) is rejected by every replica, the "
        "coordinator's write-response handler counts total replicas across ALL DCs but only "
        "tallies failure responses from the LOCAL DC. The failure-threshold check "
        "`blockFor() + failures > candidateReplicaCount()` in AbstractWriteResponseHandler "
        "therefore never trips (candidateReplicaCount() uses the all-DC replica count while "
        "`failures` only accrues local-DC failures), so the coordinator waits out the full "
        "write timeout and emits WriteTimeout (code=1100) instead of the correct WriteFailure "
        "(code=1500). On a single-DC keyspace, where total replicas == local-DC replicas, the "
        "same workload correctly yields WriteFailure. The fix (4.0.2) makes candidateReplicaCount() "
        "return the local-DC replica count when consistencyLevel().isDatacenterLocal(), so the "
        "all-replicas-rejected case crosses the failure threshold. Components: "
        "Consistency/Coordination, Messaging/Internode."
    )

    _DC1 = "cass-dc1"
    _DC2 = "cass-dc2"
    _KS = "repro16334_ks"
    _TABLE = "repro16334_ks.t"
    _MAX_MUTATION_KB = 1000
    # 'ab' * 1.1e6 = a 1.1 MB byte blob (2.2 MB hex) >> max_mutation_size_in_kb=1000 (~1 MB).
    _BLOB_REPEAT = 1100000
    _INS_FILE = "/tmp/ins16334.cql"
    # Verbatim WriteTimeout signature (buggy 4.0.1). A fixed 4.0.2 binary returns code=1500 here.
    _BUGGY_PATTERN = r"code=1100 \[Coordinator node timed out waiting for replica nodes' responses\]"

    # ── ring node command (lower max_mutation_size, disable handoff) ─────────────
    def _node_cmd(self) -> str:
        return (
            f"printf '\\nmax_mutation_size_in_kb: {self._MAX_MUTATION_KB}\\n' >> /etc/cassandra/cassandra.yaml\n"
            "sed -ri 's/^(hinted_handoff_enabled:).*/\\1 false/' /etc/cassandra/cassandra.yaml || true\n"
            "exec docker-entrypoint.sh cassandra -f\n"
        )

    def post_deploy(self):
        """Stand up the 2-DC ring: cass-dc1 (dc1 seed) + cass-dc2 (dc2), both with a lowered max mutation."""
        app = self.app
        logger.info("[16334] post_deploy: standing up 2-DC ring (dc1 seed + dc2)")
        app.apply_bare_pod(
            self._DC1,
            command=self._node_cmd(),
            env={"CASSANDRA_DC": "dc1", "CASSANDRA_RACK": "rack1"},
            set_seeds=False,
        )
        app.wait_pod_running(self._DC1, timeout=300)
        seed_ip = app.pod_ip(self._DC1)
        logger.info(f"[16334] dc1 seed IP={seed_ip}")
        app.apply_bare_pod(
            self._DC2,
            command=self._node_cmd(),
            env={"CASSANDRA_DC": "dc2", "CASSANDRA_RACK": "rack1", "CASSANDRA_SEEDS": seed_ip},
        )
        app.wait_pod_running(self._DC2, timeout=300)
        if not app.wait_ring(2, observer_pod=self._DC1, timeout=600):
            logger.warning("[16334] post_deploy: 2-DC ring did not reach 2x UN within 600s")

    def _create_schema(self):
        self.app.cqlsh(
            self._DC1,
            f"CREATE KEYSPACE IF NOT EXISTS {self._KS} WITH replication = "
            "{'class':'NetworkTopologyStrategy','dc1':1,'dc2':1}; "
            f"CREATE TABLE IF NOT EXISTS {self._TABLE} (key int PRIMARY KEY, val blob);",
        )

    def _stage_insert(self):
        """Write the LOCAL_ONE oversized-blob INSERT into a CQL file in cass-dc1 (python3, avoids ARG_MAX)."""
        script = (
            f"python3 -c \"blob='ab'*{self._BLOB_REPEAT}; "
            f"f=open('{self._INS_FILE}','w'); "
            "f.write('CONSISTENCY LOCAL_ONE;\\n'); "
            f"f.write('INSERT INTO {self._TABLE} (key, val) VALUES (1, 0x'+blob+');\\n'); "
            'f.close()"'
        )
        self.app.exec(self._DC1, script)

    def retrigger(self):
        """Idempotently (re)ensure the schema + staged blob file so the oracle's command can fire."""
        self._create_schema()
        self._stage_insert()

    @mark_fault_injected
    def inject_fault(self):
        """Create the multi-DC keyspace, stage the oversized blob, and fire the LOCAL_ONE insert once."""
        self._create_schema()
        self._stage_insert()
        out = self.app.exec(self._DC1, f"cqlsh -f {self._INS_FILE}")
        logger.info(f"[16334] inject_fault money-insert output:\n{out}")

    def build_mitigation_oracle(self):
        return CassandraLogGrepOracle(
            problem=self,
            pod=self._DC1,
            source="command",
            command=f"cqlsh -f {self._INS_FILE}",
            pattern=self._BUGGY_PATTERN,
            retrigger=True,
            attempts=3,
            retry_delay=10.0,
        )
