"""
Ungraceful Pod Termination — Discord March 2026 voice outage simulation.

Real-world story:
  On March 25, 2026, Discord suffered a 3-hour voice outage after a routine
  Kubernetes scale-down terminated 50% of session pods simultaneously.
  A safety check meant to wait for in-flight handoffs to complete caused the
  terminationGracePeriodSeconds to elapse before handoffs could begin.
  Kubernetes sent SIGKILL, dropping 17% of active sessions and cascading
  into downstream voice syncer failure.

  Reference: https://discord.com/blog/behind-the-scenes-of-the-3-25-26-voice-outage

Simulation:
  We reproduce the core failure mechanism (drain time > grace period →
  SIGKILL mid-drain → dropped in-flight requests), scoped to the hotel
  reservation app rather than Discord's full session-handoff cascade:

  1. Scale the `reservation` deployment up to a small fleet (4 replicas).
  2. Patch it with terminationGracePeriodSeconds=1 and a preStop hook that
     sleeps 30 seconds (standing in for a connection-drain/handoff step),
     using a STRATEGIC merge patch so existing container fields (image,
     ports, env, ...) are preserved. The patch is verified against the
     live object afterwards — injection raises if it did not apply.
  3. Once the faulted pods are rolled out, scale the fleet down 50%
     (4 → 2), mirroring the incident trigger. The terminating pods are
     SIGKILL'd 1s into their 30s preStop hook, resetting the in-flight
     requests generated by the workload and surfacing connection-reset /
     5xx errors in the frontend during the churn event.

  The mitigation oracle then performs a controlled test rollout under
  live traffic and requires both continuous availability and a near-zero
  request failure ratio, so the fix must actually let pods drain — a
  config-only or stub-workload "fix" does not pass.
"""

import json
import os
import tempfile

from sregym.conductor.oracles.llm_as_a_judge.llm_as_a_judge_oracle import LLMAsAJudgeOracle
from sregym.conductor.oracles.ungraceful_termination_mitigation import UngracefulTerminationMitigationOracle
from sregym.conductor.problems.base import Problem
from sregym.service.apps.hotel_reservation import HotelReservation
from sregym.service.kubectl import KubeCtl
from sregym.utils.decorators import mark_fault_injected

# Generic names — do not expose fault category to agent
_PRESLEEP_SECONDS = 30
_FAULT_GRACE_PERIOD = 1
_FLEET_REPLICAS = 4
_SCALED_DOWN_REPLICAS = 2  # 50% simultaneous termination, as in the incident


class UngracefulPodTermination(Problem):
    def __init__(self, app_name: str = "hotel_reservation"):
        self.faulty_service = "reservation"

        if app_name == "hotel_reservation":
            app = HotelReservation()
        else:
            raise ValueError(f"Unsupported app name: {app_name}")

        super().__init__(app=app)

        self.kubectl = KubeCtl()
        self._original_grace_period = 30
        self._original_replicas = 1
        self._original_lifecycle = None
        self._container_name = None

        self.root_cause = self.build_structured_root_cause(
            component=f"deployment/{self.faulty_service}",
            namespace=self.namespace,
            description=(
                f"The `{self.faulty_service}` deployment has terminationGracePeriodSeconds "
                f"set to {_FAULT_GRACE_PERIOD}, far shorter than the {_PRESLEEP_SECONDS}s "
                "required for its preStop hook to complete connection draining. "
                "When pods are terminated — as happened when the fleet was scaled "
                "down by 50% — Kubernetes sends SIGKILL before the preStop hook "
                "finishes, dropping all in-flight requests abruptly. This produces "
                "connection-reset errors in dependent services and elevated 5xx rates "
                "visible in logs and metrics during any pod churn event."
            ),
        )

        self.diagnosis_oracle = LLMAsAJudgeOracle(problem=self, expected=self.root_cause)
        self.app.deploy()
        self.mitigation_oracle = UngracefulTerminationMitigationOracle(
            problem=self,
            deployment_name=self.faulty_service,
            min_grace_period=_PRESLEEP_SECONDS,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _get_deployment_json(self) -> dict:
        output = self.kubectl.exec_command(
            f"kubectl get deployment {self.faulty_service} -n {self.namespace} -o json"
        )
        return json.loads(output)

    def _patch_deployment(self, patch: dict) -> None:
        # NOTE: intentionally uses kubectl's default STRATEGIC merge patch.
        # A JSON merge patch (--type=merge) replaces the containers list
        # wholesale, so a partial container entry would drop required fields
        # (image, ports, ...) and be rejected by the API server. Strategic
        # merge combines container entries by their `name` key instead.
        tmp_path = None
        try:
            with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
                json.dump(patch, f)
                tmp_path = f.name
            self.kubectl.exec_command(
                f"kubectl patch deployment {self.faulty_service} -n {self.namespace} "
                f"--patch-file {tmp_path}"
            )
        finally:
            if tmp_path is not None:
                os.unlink(tmp_path)

    def _scale(self, replicas: int, wait: bool = True) -> None:
        self.kubectl.exec_command(
            f"kubectl scale deployment/{self.faulty_service} "
            f"-n {self.namespace} --replicas={replicas}"
        )
        if wait:
            self.kubectl.exec_command(
                f"kubectl rollout status deployment/{self.faulty_service} "
                f"-n {self.namespace} --timeout=180s"
            )

    def _live_pod_spec(self) -> dict:
        return self._get_deployment_json()["spec"]["template"]["spec"]

    def _verify_fault_applied(self) -> None:
        """KubeCtl.exec_command suppresses kubectl errors, so a rejected
        patch would otherwise go unnoticed. Verify against the live object
        and fail loudly if the fault is not actually present."""
        pod_spec = self._live_pod_spec()
        container = pod_spec["containers"][0]
        grace = pod_spec.get("terminationGracePeriodSeconds")
        pre_stop = (container.get("lifecycle") or {}).get("preStop")

        if grace != _FAULT_GRACE_PERIOD or not pre_stop:
            raise RuntimeError(
                f"Fault injection patch was not applied to {self.faulty_service} "
                f"(grace={grace}, preStop={'present' if pre_stop else 'missing'}). "
                "Check kubectl patch output for API server rejections."
            )
        if not container.get("image"):
            raise RuntimeError(
                "Fault injection corrupted the container spec (image missing)"
            )

    # ------------------------------------------------------------------
    # Fault lifecycle
    # ------------------------------------------------------------------

    @mark_fault_injected
    def inject_fault(self):
        print("== Fault Injection ==")

        # Save original deployment state
        deployment = self._get_deployment_json()
        pod_spec = deployment["spec"]["template"]["spec"]
        self._original_grace_period = pod_spec.get("terminationGracePeriodSeconds", 30)
        self._original_replicas = deployment["spec"].get("replicas", 1)
        self._container_name = pod_spec["containers"][0]["name"]
        self._original_lifecycle = pod_spec["containers"][0].get("lifecycle")

        # 1. Scale up to a fleet so a 50% scale-down is meaningful
        print(f"⏫ Scaling {self.faulty_service} to {_FLEET_REPLICAS} replicas...")
        self._scale(_FLEET_REPLICAS)

        # 2. Inject: short grace period + slow preStop (drain/handoff stand-in)
        patch = {
            "spec": {
                "template": {
                    "spec": {
                        "terminationGracePeriodSeconds": _FAULT_GRACE_PERIOD,
                        "containers": [
                            {
                                "name": self._container_name,
                                "lifecycle": {
                                    "preStop": {
                                        "exec": {
                                            "command": [
                                                "/bin/sh",
                                                "-c",
                                                f"sleep {_PRESLEEP_SECONDS}",
                                            ]
                                        }
                                    }
                                },
                            }
                        ],
                    }
                }
            }
        }
        self._patch_deployment(patch)
        self._verify_fault_applied()

        # Wait for the faulted pods to roll out. (The pods being replaced
        # here still terminate under the ORIGINAL grace period; the fault
        # becomes observable on the next churn event below.)
        self.kubectl.exec_command(
            f"kubectl rollout status deployment/{self.faulty_service} "
            f"-n {self.namespace} --timeout=180s"
        )

        # 3. Reproduce the incident trigger: terminate 50% of the fleet at
        #    once. These pods are SIGKILL'd 1s into their 30s preStop hook,
        #    dropping the workload's in-flight requests.
        print(
            f"⏬ Scaling down {_FLEET_REPLICAS} → {_SCALED_DOWN_REPLICAS} "
            "(50% simultaneous termination)..."
        )
        self._scale(_SCALED_DOWN_REPLICAS, wait=False)

        print(
            f"Injected ungraceful termination fault on: {self.faulty_service} "
            f"(terminationGracePeriodSeconds={_FAULT_GRACE_PERIOD}, "
            f"preStop sleep={_PRESLEEP_SECONDS}s, scale-down "
            f"{_FLEET_REPLICAS}→{_SCALED_DOWN_REPLICAS})"
        )
        print(f"Service: {self.faulty_service} | Namespace: {self.namespace}")

    @mark_fault_injected
    def recover_fault(self):
        print("== Fault Recovery ==")

        container_name = self._container_name
        if container_name is None:
            container_name = self._live_pod_spec()["containers"][0]["name"]

        # Restore original grace period and lifecycle. With a strategic
        # merge patch, a null lifecycle DELETES the field, so this is
        # correct whether or not the container originally had one.
        patch = {
            "spec": {
                "template": {
                    "spec": {
                        "terminationGracePeriodSeconds": self._original_grace_period,
                        "containers": [
                            {
                                "name": container_name,
                                "lifecycle": self._original_lifecycle,
                            }
                        ],
                    }
                }
            }
        }
        self._patch_deployment(patch)

        # Restore the original replica count
        self._scale(self._original_replicas, wait=False)

        # Wait for rollout to settle
        self.kubectl.exec_command(
            f"kubectl rollout status deployment/{self.faulty_service} "
            f"-n {self.namespace} --timeout=180s"
        )

        # Verify recovery actually landed (exec_command may hide failures)
        pod_spec = self._live_pod_spec()
        grace = pod_spec.get("terminationGracePeriodSeconds", 30)
        lifecycle = pod_spec["containers"][0].get("lifecycle")
        if grace != self._original_grace_period or lifecycle != self._original_lifecycle:
            raise RuntimeError(
                f"Fault recovery did not restore original spec "
                f"(grace={grace}, lifecycle={'present' if lifecycle else 'absent'})"
            )

        print(f"Recovered ungraceful termination fault on: {self.faulty_service}")
        print(f"Service: {self.faulty_service} | Namespace: {self.namespace}")