apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-cluster
  namespace: cockroachdb
  annotations:
    crdb.cockroachlabs.com/initialize: "required"
spec:
  nodes: 3
  image:
    name: cockroachdb/cockroach:v24.1.0
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  tlsEnabled: false
  grpcPort: 26257
  httpPort: 8080
status:
  clusterStatus: Deployed
