apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-cluster
  namespace: cockroachdb
  annotations:
    crdb.cockroachlabs.com/decommission: "scale-down-to-2"
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi
  tlsEnabled: false
  image:
    name: cockroachdb/cockroach:v24.1.0
  nodes: 2
status:
  clusterStatus: Initialized
