"""Narrow private receipt IO for fresh checks performed inside the verifier.

The owner persists provenance, not verdicts. This object is transported only as
a resource handle over the existing trusted container pipe.
"""

import hashlib
from urllib.parse import urlsplit

from sregym.generators.workload.codehub import ReceiptLedger, canonical, operation_from_row


class CodeHubVerificationJournal:
    OPERATIONS = {
        "journal_begin_epoch": ("begin_epoch", 0),
        "journal_request": ("request", 5),
        "journal_acknowledge": ("acknowledge", 6),
        "journal_reject": ("reject", 5),
        "journal_close_epoch": ("close_epoch", 1),
        "journal_delivery_receipts": ("delivery_receipts", 1),
    }

    def __init__(self, ledger: ReceiptLedger, tenant_groups: dict[str, str], *, observer=None):
        ledger.partition_cuts(tenant_groups)
        self.ledger = ledger
        self.tenant_groups = dict(tenant_groups)
        self._epochs = set()
        self.observer = observer

    def delivery_receipts(self, identities) -> dict:
        if self.observer is None or type(identities) not in (list, tuple) or not 0 < len(identities) <= 100:
            raise ValueError("Independent receiver observation needs a bounded actual-receipt batch")
        rows = self.observer.observations(tuple(identities))
        return {"receipts": list(rows)}

    def begin_epoch(self) -> int:
        epoch = self.ledger.begin_epoch()
        self._epochs.add(epoch)
        return epoch

    def _epoch(self, epoch):
        if type(epoch) is not int or epoch not in self._epochs:
            raise ValueError("Fresh IO must belong to an owner-allocated verifier epoch")

    def request(self, epoch, group, operation, effects, provenance=None) -> bool:
        self._epoch(epoch)
        op = operation_from_row(operation)
        if self.tenant_groups.get(op.tenant_id) != group:
            raise ValueError("Fresh request differs from frozen tenant routing")
        # Expected content comes from verifier-generated bytes before HTTP/Git IO.
        self.ledger.request(op, epoch, effects=effects, provenance=provenance)
        return True

    def acknowledge(self, epoch, event_id, origin, latency_ms, status_code, receipt) -> bool:
        self._epoch(epoch)
        operation = self.ledger.requested_operation(event_id, epoch)
        expected = operation.observed_row()
        digest = hashlib.sha256(canonical(expected).encode()).hexdigest()
        if (
            type(receipt) is not dict
            or any(receipt.get(key) != value for key, value in expected.items())
            or receipt.get("record_key") != operation.record_key
            or receipt.get("operation_sha256") != digest
            or type(receipt.get("replayed")) is not bool
            or type(receipt.get("region")) is not str
            or not receipt["region"]
        ):
            raise ValueError("Fresh acknowledgment differs from the full requested operation")
        self._origin(origin)
        self.ledger.acknowledge(event_id, origin, latency_ms, status_code)
        return True

    def reject(self, epoch, event_id, origin, latency_ms, status_code) -> bool:
        self._epoch(epoch)
        self.ledger.requested_operation(event_id, epoch)
        self._origin(origin)
        self.ledger.reject(event_id, origin, latency_ms, status_code)
        return True

    @staticmethod
    def _origin(origin):
        if type(origin) is not str or len(origin) > 2048:
            raise ValueError("Invalid bounded ordinary API origin")
        parsed = urlsplit(origin)
        if parsed.scheme not in {"http", "https"} or not parsed.hostname or parsed.username or parsed.password:
            raise ValueError("Invalid ordinary API origin")

    def close_epoch(self, epoch) -> bool:
        self._epoch(epoch)
        self.ledger.close_epoch(epoch)
        return True
